# Generated by Django 2.2.1 on 2019-05-30 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quality_leads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='state',
            old_name='email',
            new_name='sio_email',
        ),
    ]
